export const mockPriceData = [
  {
    product_id: "83K0006FLM",
    name: "Laptop Lenovo Legion 5 Pro RTX 4060",
    store: "Falabella",
    price_real: 4500,
    price_ia: 5200,
    ahorro_pct: 15.5,
    veredicto: " SUPER OFERTA",
    specs: { cpu: "Core i7", ram: "16GB", gpu: "RTX 4060" },
  },
  {
    product_id: "93K0007GLM",
    name: "Dell XPS 13 Plus i7 RTX 4050",
    store: "Amazon",
    price_real: 3800,
    price_ia: 4100,
    ahorro_pct: 7.3,
    veredicto: "BUEN PRECIO",
    specs: { cpu: "Core i7", ram: "8GB", gpu: "RTX 4050" },
  },
  {
    product_id: "103K0008HLM",
    name: "ASUS VivoBook 16 Ryzen 7",
    store: "Paris",
    price_real: 2900,
    price_ia: 3500,
    ahorro_pct: 17.1,
    veredicto: " SUPER OFERTA",
    specs: { cpu: "Ryzen 7", ram: "16GB", gpu: "Integrated" },
  },
  {
    product_id: "113K0009ILM",
    name: "HP Pavilion 15 Ryzen 5",
    store: "Ripley",
    price_real: 5200,
    price_ia: 4500,
    ahorro_pct: -15.5,
    veredicto: "SOBREPRECIO",
    specs: { cpu: "Ryzen 5", ram: "8GB", gpu: "Integrated" },
  },
  {
    product_id: "123K0010JLM",
    name: 'MacBook Air M3 13"',
    store: "Bip",
    price_real: 6500,
    price_ia: 7200,
    ahorro_pct: 9.7,
    veredicto: "BUEN PRECIO",
    specs: { cpu: "M3", ram: "8GB", gpu: "Integrated" },
  },
  {
    product_id: "133K0011KLM",
    name: "Lenovo ThinkBook 13 i5",
    store: "Falabella",
    price_real: 2100,
    price_ia: 2400,
    ahorro_pct: 12.5,
    veredicto: " SUPER OFERTA",
    specs: { cpu: "Core i5", ram: "8GB", gpu: "Integrated" },
  },
  {
    product_id: "143K0012LLM",
    name: "ACER Aspire 5 Ryzen 7",
    store: "Amazon",
    price_real: 3100,
    price_ia: 3300,
    ahorro_pct: 6.1,
    veredicto: "BUEN PRECIO",
    specs: { cpu: "Ryzen 7", ram: "16GB", gpu: "RTX 3050" },
  },
  {
    product_id: "153K0013MLM",
    name: "MSI Bravo 15 RTX 4050",
    store: "Paris",
    price_real: 4200,
    price_ia: 5100,
    ahorro_pct: 17.6,
    veredicto: " SUPER OFERTA",
    specs: { cpu: "Core i7", ram: "16GB", gpu: "RTX 4050" },
  },
  {
    product_id: "163K0014NLM",
    name: "Razer Book 13 RTX 4060",
    store: "Ripley",
    price_real: 6800,
    price_ia: 6200,
    ahorro_pct: -9.7,
    veredicto: "SOBREPRECIO",
    specs: { cpu: "Core i7", ram: "16GB", gpu: "RTX 4060" },
  },
  {
    product_id: "173K0015OLM",
    name: "Samsung Galaxy Book3 Pro",
    store: "Bip",
    price_real: 5500,
    price_ia: 6100,
    ahorro_pct: 9.8,
    veredicto: "BUEN PRECIO",
    specs: { cpu: "Core i7", ram: "16GB", gpu: "RTX 4060" },
  },
  {
    product_id: "183K0016PLM",
    name: "LG Gram 16 i7",
    store: "Falabella",
    price_real: 2700,
    price_ia: 3400,
    ahorro_pct: 20.6,
    veredicto: " SUPER OFERTA",
    specs: { cpu: "Core i7", ram: "16GB", gpu: "Integrated" },
  },
  {
    product_id: "193K0017QLM",
    name: "Huawei MateBook 14s",
    store: "Amazon",
    price_real: 3900,
    price_ia: 4200,
    ahorro_pct: 7.1,
    veredicto: "BUEN PRECIO",
    specs: { cpu: "Core i7", ram: "16GB", gpu: "Integrated" },
  },
  {
    product_id: "203K0018RLM",
    name: "OnePlus Pad Pro",
    store: "Paris",
    price_real: 2300,
    price_ia: 2800,
    ahorro_pct: 17.9,
    veredicto: " SUPER OFERTA",
    specs: { cpu: "Snapdragon", ram: "12GB", gpu: "Adreno" },
  },
  {
    product_id: "213K0019SLM",
    name: "ASUS ROG Zephyrus",
    store: "Ripley",
    price_real: 7200,
    price_ia: 6500,
    ahorro_pct: -10.8,
    veredicto: "SOBREPRECIO",
    specs: { cpu: "Core i9", ram: "32GB", gpu: "RTX 4090" },
  },
  {
    product_id: "223K0020TLM",
    name: "Apple MacBook Pro 16 M3",
    store: "Bip",
    price_real: 8900,
    price_ia: 9200,
    ahorro_pct: 3.3,
    veredicto: "BUEN PRECIO",
    specs: { cpu: "M3 Max", ram: "36GB", gpu: "Integrated" },
  },
  {
    product_id: "233K0021ULM",
    name: "Lenovo IdeaPad 5 Ryzen",
    store: "Falabella",
    price_real: 1800,
    price_ia: 2100,
    ahorro_pct: 14.3,
    veredicto: " SUPER OFERTA",
    specs: { cpu: "Ryzen 5", ram: "8GB", gpu: "Integrated" },
  },
  {
    product_id: "243K0022VLM",
    name: "HP Spectre x360 i7",
    store: "Amazon",
    price_real: 4800,
    price_ia: 5200,
    ahorro_pct: 7.7,
    veredicto: "BUEN PRECIO",
    specs: { cpu: "Core i7", ram: "16GB", gpu: "RTX 4050" },
  },
  {
    product_id: "253K0023WLM",
    name: "Dell Inspiron 15 i5",
    store: "Paris",
    price_real: 2400,
    price_ia: 2900,
    ahorro_pct: 17.2,
    veredicto: " SUPER OFERTA",
    specs: { cpu: "Core i5", ram: "8GB", gpu: "Integrated" },
  },
  {
    product_id: "263K0024XLM",
    name: "Acer Swift 3 Ryzen 7",
    store: "Ripley",
    price_real: 3200,
    price_ia: 3600,
    ahorro_pct: 11.1,
    veredicto: "BUEN PRECIO",
    specs: { cpu: "Ryzen 7", ram: "16GB", gpu: "Integrated" },
  },
]
